<template>
  <div id="newGame">
    <Board
      code="ess3ww3ss4sssswwsssssssswwssss3ss1ww2ss3wwwwwwwwwwwwwwwwwwww3ss2ww4ss3sssswwsssssssswwssss1ss3ww3ssdsssswwsssssssswwsssssssswwsssssss0wwsssssssswwsssssssswwsssssssswwsssssssswwsssssssswwssss0ssswwsssswwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwsss0wwwwwwsssswwwwwwsssswwwwww0ssswwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwsss0ww0ssssssswwsssssssswwssss0ssswwsss0wwwwwwwwwwwwwwwwwwww0ssswwsss0sssswwsssssssswwsssssss0ww0ssssssswwsss0sssswwsssssssswwsssssssswwsssssssswwsssssssswwssssssssww0ssssssswwsssssssswwsssssssswwssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss "
    />
  </div>
</template>

<script>
import Board from "@/components/board.vue";
export default {
  name: "NewGame",
  components: {
    Board
  }
};
</script>

<style scoped>
#newGame {
  background-color: #e0dad5;
  width: 100vw;
  height: 100%;
}
</style>
